# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yooncobra의 블로그 입니다
email: yooncobra@gmail.com
description: 'FrontEnd 개발에 대한 경험과 Review를 공유하는 Yooncobra의 기술블로그입니다'
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
github_username: 'yooncobra'

# Build settings
markdown: kramdown

# highlighter: pygments

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
